name: Test `npm-versions` action
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grab versions from npmjs.org
        id: get_versions
        uses: ./ # Uses an action in the root directory
        with:
          package: emoji-hash
      - name: Echo output
        run: |
          echo "${{ steps.get_versions.outputs.versions }}"
          test "${{ steps.get_versions.outputs.versions }}" = "[1.0.0,1.1.0,1.2.0,1.2.1,1.3.0]"

  test-detailed:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grab detailed versions from npmjs.org
        id: get_versions
        uses: ./ # Uses an action in the root directory
        with:
          package: emoji-hash
          details: 'true'
      - name: Echo output
        run: |
          echo "${{ steps.get_versions.outputs.versions }}"
          test "${{ steps.get_versions.outputs.versions }}" = "[{version:1.0.0,published_at:2016-04-15T02:26:00.141Z},{version:1.1.0,published_at:2016-04-15T03:06:20.334Z},{version:1.2.0,published_at:2016-04-19T05:39:17.391Z},{version:1.2.1,published_at:2016-06-17T09:05:32.462Z},{version:1.3.0,published_at:2017-06-08T04:21:08.821Z}]"

  test-sorted:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grab detailed versions from npmjs.org
        id: get_versions
        uses: ./ # Uses an action in the root directory
        with:
          package: emoji-hash
          sortVersions: 'desc'
      - name: Echo output
        run: |
          echo "${{ steps.get_versions.outputs.versions }}"
          test "${{ steps.get_versions.outputs.versions }}" = "[1.3.0,1.2.1,1.2.0,1.1.0,1.0.0]"
